config/routes.rb
Rails.application.routes.draw do
  # get '/blogs', to: "blogs#index"
  # get '/blogs/new', to: "blogs#new"
  # get '/', to: "blogs#index"
  root "blogs#index"
  resources :blogs

  get "/signup", to: "users#new", as: "signup"
  resource :users, only: :create

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
  has_many :tags

  def tags_names
    # self.tags.pluck(:name).join(", ")
    array = []
    self.tags.each do |tag|
      array << tag.name
    end
    array.join(", ")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  before_save :downcase_email
  has_many :blogs

  private
    def downcase_email
      self.email = self.email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  private
    def authenticate_user!
      unless user_logged_in?
        flash[:warning] = "Please login!"
        redirect_to login_path 
      end
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :edit_for_new_blogs, only: [:edit, :update]
  before_action :check_correct_user, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    # @blog = Blog.new(blog_params.merge(user: current_user))
    # @blog = Blog.new(blog_params.merge(user_id: current_user.id))
    @blog = current_user.blogs.new(blog_params)
    if @blog.save

      params[:blog][:tags_names].gsub(/ /, "").split(",").each do |tag_name|
        @blog.tags.create(name: tag_name)
      end
      #same as "/blogs/#{@blog.id}"
      #same as blog_path(@blog)
      redirect_to @blog
    else
      render :new
    end
  end

  def show
    # @blog.increment(:view_count)
    @blog.view_count += 1
    @blog.save
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      @blog.tags.destroy_all
      params[:blog][:tags_names].gsub(/ /, "").split(",").each do |tag_name|
        @blog.tags.create(name: tag_name)
      end
      redirect_to @blog
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :body)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end

    def edit_for_new_blogs
      redirect_to blogs_path if @blog.view_count > 10
    end

    def check_correct_user
      unless @blog.user == current_user
        flash[:danger] = "Unauthorized"
        redirect_to blogs_path 
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user!, only: []
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "You have successfully signed in"
      redirect_to root_path
    else
      redirect_to login_path, notice: "Invalid email or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :username, :password,
        :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    end
  end

  def user_logged_in?
    current_user.present?
  end
end

app/views/blogs/edit.html.erb
<h2>Edit Blog</h2>

<%= form_for @blog do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <br />

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <br />

  <div>
    <%= f.label :tags %>
    <%= f.text_field :tags_names, placeholder: "food, something, car" %>
  </div>

  <br />
  
  <div>
    <%= f.submit "Update Blog!", class: "btn btn-info" %>
  </div>
<% end %>

app/views/blogs/index.html.erb
<h1>Blog Index</h1>

<% @blogs.each_with_index do |blog, index| %>
  <div>

    <%= link_to blog do %>
      <span><%= "#{index + 1}. #{blog.title.truncate(15)}" %></span>
    <% end %>

    <span><%= "Written by: #{blog.user.username}" %></span>
  </div>
<% end %>

<%= link_to "Post a new blog", new_blog_path, class: "btn btn-info" %>

app/views/blogs/new.html.erb
<h2>New Blog</h2>

<%= form_for @blog do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <br />

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <br />

  <div>
    <%= f.label :tags %>
    <%= f.text_field :tags_names, placeholder: "food, something, car" %>
  </div>

  <br />

  <div>
    <%= f.submit "Create Blog!", class: "btn btn-info" %>
  </div>
<% end %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %>
  <span style="font-size: 12px;">(<%= @blog.view_count%> views)</span>
</h1>

<p><%= @blog.body %></p>

<p>Tags: <%= @blog.tags_names %></p>

<%= link_to "Edit", edit_blog_path(@blog), class: "btn btn-success" %>
<%= link_to "Delete", blog_path(@blog), method: :delete, class: "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <span>
      <%= link_to "Home", root_path %>
    </span>
    <% if user_logged_in? %>
      <span>
        <%= link_to "Logout", logout_path, method: :delete %>
      </span>
      <span>
        <%= "Hello, #{current_user.username}" %>
      </span>
    <% else %>
      <span>
        <%= link_to "Signup", signup_path %>
      </span>
      <span>
        <%= link_to "Login", login_path %>
      </span>
    <% end %>
  </div>

  <div>
    <table class="table">
      <% flash.each do |k, v| %>
        <tr class="<%= k %>">
          <td><%= v %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |e| %>
    <p><%= e %></p>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit "Sign Up!", class: "btn btn-default" %>
  </div>
<% end %>